defmodule TrogonPresence.Tracker do
  @moduledoc """
  The runtime behind a `use TrogonPresence` module: one process per presence
  module, registered under that module's own name, that

    * starts a `TrogonPresence.Reader` the first time a topic is tracked,
      listed or looked up, and keeps its installed snapshot in process state
      (the "ETS replica" worklist item lives here as plain process state
      rather than a separate ETS table, since this process is already the
      only reader and writer of it; see the module-level trade-off note
      below);
    * monitors every pid that calls `track/4` and releases its entries with
      the service when that pid goes down, the same way `Phoenix.Tracker`
      releases on a channel crash;
    * re-heartbeats every locally tracked entry on a fixed interval, grouped
      by `TrogonPresence.Key` the way `Writer.heartbeat/4` expects;
    * rebroadcasts every reader diff as a `"presence_diff"` via
      `Phoenix.PubSub`, shaped by `TrogonPresence.Broadcast`, and does the
      same for whatever a reader's later snapshot changed against the
      replica it replaces (a resnapshot after a reconnect or a gap), so a
      channel client still sees every net change exactly once.

  ## Backends

  This process runs under `:nats`, `:dual` and `:nats_read` (`:phoenix` is a
  pure `Phoenix.Presence` passthrough generated by `TrogonPresence` and never
  reaches this module at all). In `:dual` and `:nats_read`, every `track/4`
  and `update/4` call first goes to a nested real `Phoenix.Presence` module
  given to this process as `:phoenix_mirror`; this process then mirrors that
  write to NATS, best-effort. A `Tracked` entry's `mirrored?` flag says
  whether that mirror write is currently in place; a heartbeat tick retries
  it for any entry where it is not, as long as the entry's meta validated
  against this shim's own rules in the first place (one that never did,
  because `Phoenix.Presence` accepts metadata this shim's wire format
  cannot, stays unmirrored for its whole lifetime). See `TrogonPresence`'s
  moduledoc for the trade-offs this trades for.

  `:dual` never starts a `TrogonPresence.Reader`: its reads and broadcasts
  come entirely from the nested `Phoenix.Presence`, so this process's reader
  bookkeeping (`presences`, `readers`, `reader_pids`) simply stays empty for
  it. `:nats_read` starts a reader exactly like `:nats` does; its nested
  `Phoenix.Presence` is wired to a `Phoenix.PubSub` nothing else subscribes
  to, so its own broadcasts never reach a real client.

  ## Trade-offs against `Phoenix.Presence`

  `fetch/2` for `:nats` and `:nats_read` runs on a `Task.Supervisor` child
  started alongside this process, matching `Phoenix.Presence`'s own
  `:rest_for_one` shape, so a slow `fetch/2` cannot block the next `track`,
  `update` or diff this process handles. `:dual` applies `fetch/2` directly
  in the calling process instead, after the nested `Phoenix.Presence`'s own
  (already async) read returns, since there is no shared process on that
  read path to protect.

  A `Writer.heartbeat/4` reply carries one status per submitted entry. On
  `"gone"` or `"conflict"` (the service no longer recognizes that holder,
  typically after a GC pause or a partition outlasted the lease), this
  process re-tracks the entry under a fresh `HolderId` rather than letting it
  disappear for good; `"unavailable"` is left for the next tick's natural
  retry. A re-track changes the entry's `phx_ref`, so a caller still holding
  the `phx_ref` returned by its original `track/4` or `update/4` call will
  find that reference stale after a lease loss.

  ## Disconnects

  A NATS disconnect never takes this process down, because a crash here
  would drop every presence tracked on the node and turn one network blip
  into a leave for each of them. While the connection is gone, `track/4`
  and `update/4` return `{:error, {:transport, reason}}` (see
  `TrogonPresence.Writer`) and leave existing entries as they were; a
  heartbeat tick logs its failure and the next tick retries. `untrack/3`
  keeps `Phoenix.Presence`'s `:ok` contract and drops the entry locally;
  a release the service never saw expires with its own lease. Once the
  connection is back, heartbeats land again, and any entry the service
  reclaimed in the meantime comes back through the `"gone"`/`"conflict"`
  re-track above.
  """

  use GenServer
  require Logger

  alias TrogonPresence.Tracker.Tracked
  alias TrogonPresence.Snapshot.Limits
  alias TrogonPresence.Wire.HeartbeatReply

  alias TrogonPresence.{
    Broadcast,
    Diff,
    HolderId,
    Key,
    Meta,
    Presences,
    Reader,
    ShardCount,
    StoredRef,
    Topic,
    Writer
  }

  @default_heartbeat_ms :timer.seconds(10)

  @enforce_keys [
    :module,
    :conn,
    :pubsub_server,
    :dispatcher,
    :connection,
    :reader_key,
    :shards,
    :limits,
    :heartbeat_ms,
    :backend,
    :task_supervisor
  ]
  defstruct [
    :module,
    :conn,
    :pubsub_server,
    :dispatcher,
    :connection,
    :reader_key,
    :shards,
    :limits,
    :heartbeat_ms,
    :resnapshot_ms,
    :backend,
    :phoenix_mirror,
    :task_supervisor,
    readers: %{},
    reader_pids: %{},
    presences: %{},
    tracked: %{},
    tracked_monitors: %{}
  ]

  @spec start_link(module(), keyword()) :: GenServer.on_start()
  def start_link(module, opts) do
    GenServer.start_link(__MODULE__, {module, opts}, name: module)
  end

  @spec track(module(), pid(), String.t(), String.t(), map()) ::
          {:ok, binary()} | {:error, term()}
  def track(module, pid, topic, key, meta),
    do: GenServer.call(module, {:track, pid, topic, key, meta})

  @spec untrack(module(), pid(), String.t(), String.t()) :: :ok
  def untrack(module, pid, topic, key), do: GenServer.call(module, {:untrack, pid, topic, key})

  @spec update(module(), pid(), String.t(), String.t(), map() | (map() -> map())) ::
          {:ok, binary()} | {:error, term()}
  def update(module, pid, topic, key, meta_or_fun),
    do: GenServer.call(module, {:update, pid, topic, key, meta_or_fun})

  @spec list(module(), String.t(), (String.t(), map() -> map())) :: map()
  def list(module, topic, fetch), do: GenServer.call(module, {:list, topic, fetch})

  @spec get_by_key(module(), String.t(), String.t(), (String.t(), map() -> map())) :: term()
  def get_by_key(module, topic, key, fetch),
    do: GenServer.call(module, {:get_by_key, topic, key, fetch})

  @impl GenServer
  def init({module, opts}) do
    conn = Keyword.fetch!(opts, :conn)
    pubsub_server = Keyword.fetch!(opts, :pubsub_server)
    dispatcher = Keyword.get(opts, :dispatcher, Phoenix.Channel.Server)
    shards = Keyword.get(opts, :shards, ShardCount.default())
    limits = Keyword.get(opts, :limits, Limits.default())
    heartbeat_ms = Keyword.get(opts, :heartbeat_ms, @default_heartbeat_ms)
    resnapshot_ms = Keyword.get(opts, :resnapshot_ms)
    backend = Keyword.get(opts, :backend, :nats)
    phoenix_mirror = Keyword.get(opts, :phoenix_mirror)
    task_supervisor = Keyword.fetch!(opts, :task_supervisor)

    connection = TrogonPresence.ConnectionId.generate()
    reader_key = Key.new!("reader:#{connection}")

    Process.send_after(self(), :heartbeat_tick, heartbeat_ms)

    {:ok,
     %__MODULE__{
       module: module,
       conn: conn,
       pubsub_server: pubsub_server,
       dispatcher: dispatcher,
       connection: connection,
       reader_key: reader_key,
       shards: shards,
       limits: limits,
       heartbeat_ms: heartbeat_ms,
       resnapshot_ms: resnapshot_ms,
       backend: backend,
       phoenix_mirror: phoenix_mirror,
       task_supervisor: task_supervisor
     }}
  end

  @impl GenServer
  def handle_call({:track, pid, topic_raw, key_raw, meta_map}, _from, state) do
    tracked_key = {pid, topic_raw, to_string(key_raw)}

    case state.backend do
      :nats ->
        if Map.has_key?(state.tracked, tracked_key) do
          {:reply, {:error, {:already_tracked, pid, topic_raw, to_string(key_raw)}}, state}
        else
          do_track(state, tracked_key, pid, topic_raw, key_raw, meta_map)
        end

      backend when backend in [:dual, :nats_read] ->
        do_track_mirrored(state, tracked_key, pid, topic_raw, key_raw, meta_map, backend)
    end
  end

  def handle_call({:untrack, pid, topic_raw, key_raw}, _from, state) do
    tracked_key = {pid, topic_raw, to_string(key_raw)}

    case state.backend do
      :nats ->
        untrack_nats(state, tracked_key)

      backend when backend in [:dual, :nats_read] ->
        untrack_mirrored(state, tracked_key, pid, topic_raw, key_raw)
    end
  end

  def handle_call({:update, pid, topic_raw, key_raw, meta_or_fun}, _from, state) do
    tracked_key = {pid, topic_raw, to_string(key_raw)}

    case state.backend do
      :nats ->
        case Map.fetch(state.tracked, tracked_key) do
          {:ok, tracked} -> handle_update(state, tracked_key, tracked, meta_or_fun)
          :error -> {:reply, {:error, :nopresence}, state}
        end

      backend when backend in [:dual, :nats_read] ->
        handle_update_mirrored(state, tracked_key, pid, topic_raw, key_raw, meta_or_fun, backend)
    end
  end

  def handle_call({:list, topic_raw, fetch}, from, state) do
    case Topic.new(topic_raw) do
      {:ok, topic} ->
        state = ensure_reader(state, topic)
        grouped = state.presences |> Map.get(topic_raw, %{}) |> Broadcast.presences()
        dispatch_fetch(state, from, fn -> fetch.(topic_raw, grouped) end)
        {:noreply, state}

      {:error, _reason} ->
        {:reply, %{}, state}
    end
  end

  def handle_call({:get_by_key, topic_raw, key_raw, fetch}, from, state) do
    case Topic.new(topic_raw) do
      {:ok, topic} ->
        state = ensure_reader(state, topic)
        string_key = to_string(key_raw)
        grouped = state.presences |> Map.get(topic_raw, %{}) |> Broadcast.presences()

        case Map.fetch(grouped, string_key) do
          {:ok, %{metas: metas}} ->
            dispatch_fetch(state, from, fn ->
              %{^string_key => fetched} = fetch.(topic_raw, %{string_key => %{metas: metas}})
              fetched
            end)

            {:noreply, state}

          :error ->
            {:reply, [], state}
        end

      {:error, _reason} ->
        {:reply, [], state}
    end
  end

  defp dispatch_fetch(state, from, fun) do
    Task.Supervisor.start_child(state.task_supervisor, fn -> GenServer.reply(from, fun.()) end)
  end

  defp do_track(state, tracked_key, pid, topic_raw, key_raw, meta_map) do
    with {:ok, topic} <- Topic.new(topic_raw),
         {:ok, key} <- Key.new(to_string(key_raw)),
         {:ok, meta} <- Meta.new(meta_map) do
      holder = HolderId.generate()
      state = ensure_reader(state, topic)

      case Writer.track(state.conn, key, state.connection, topic, holder, meta) do
        {:ok, written} ->
          tracked = %Tracked{
            pid: pid,
            topic_raw: topic_raw,
            key_raw: to_string(key_raw),
            holder: holder,
            lifetime: written.lifetime,
            mutation_seq: written.mutation_seq,
            meta: meta,
            phx_ref: written.phx_ref,
            mirrored?: true,
            topic: topic,
            key: key
          }

          state = put_tracked(state, tracked_key, tracked)
          {:reply, {:ok, StoredRef.to_string(written.phx_ref)}, state}

        {:error, reason} ->
          {:reply, {:error, reason}, state}
      end
    else
      {:error, reason} -> {:reply, {:error, reason}, state}
    end
  end

  defp do_track_mirrored(state, tracked_key, pid, topic_raw, key_raw, meta_map, backend) do
    key_string = to_string(key_raw)

    case state.phoenix_mirror.track(pid, topic_raw, key_string, meta_map) do
      {:ok, phoenix_ref} ->
        state = maybe_ensure_reader(state, backend, topic_raw)
        tracked = mirror_track(state, pid, topic_raw, key_string, meta_map)
        state = put_tracked(state, tracked_key, tracked)
        public_ref = public_ref(backend, tracked, phoenix_ref)
        {:reply, {:ok, public_ref}, state}

      {:error, reason} ->
        {:reply, {:error, reason}, state}
    end
  end

  defp mirror_track(state, pid, topic_raw, key_string, meta_map) do
    with {:ok, topic} <- Topic.new(topic_raw),
         {:ok, key} <- Key.new(key_string),
         {:ok, meta} <- Meta.new(meta_map) do
      holder = HolderId.generate()

      case Writer.track(state.conn, key, state.connection, topic, holder, meta) do
        {:ok, written} ->
          %Tracked{
            pid: pid,
            topic_raw: topic_raw,
            key_raw: key_string,
            meta: meta,
            phx_ref: written.phx_ref,
            mirrored?: true,
            topic: topic,
            key: key,
            holder: holder,
            lifetime: written.lifetime,
            mutation_seq: written.mutation_seq
          }

        {:error, reason} ->
          Logger.warning(
            "could not mirror a track to NATS for #{topic_raw}/#{key_string}: #{inspect(reason)}"
          )

          %Tracked{
            pid: pid,
            topic_raw: topic_raw,
            key_raw: key_string,
            meta: meta,
            phx_ref: nil,
            mirrored?: false
          }
      end
    else
      {:error, reason} ->
        Logger.warning(
          "a Phoenix-accepted track could not be validated for the NATS mirror at #{topic_raw}/#{key_string}: #{inspect(reason)}"
        )

        %Tracked{
          pid: pid,
          topic_raw: topic_raw,
          key_raw: key_string,
          meta: nil,
          phx_ref: nil,
          mirrored?: false
        }
    end
  end

  defp public_ref(:dual, _tracked, phoenix_ref), do: phoenix_ref

  defp public_ref(:nats_read, %Tracked{mirrored?: true, phx_ref: phx_ref}, _phoenix_ref),
    do: StoredRef.to_string(phx_ref)

  defp public_ref(:nats_read, %Tracked{mirrored?: false}, phoenix_ref), do: phoenix_ref

  defp maybe_ensure_reader(state, :dual, _topic_raw), do: state

  defp maybe_ensure_reader(state, :nats_read, topic_raw) do
    case Topic.new(topic_raw) do
      {:ok, topic} -> ensure_reader(state, topic)
      {:error, _reason} -> state
    end
  end

  defp untrack_nats(state, tracked_key) do
    case Map.fetch(state.tracked, tracked_key) do
      {:ok, tracked} ->
        Writer.untrack(
          state.conn,
          tracked.key,
          state.connection,
          tracked.topic,
          tracked.holder,
          tracked.lifetime,
          tracked.mutation_seq
        )

        {:reply, :ok, drop_tracked(state, tracked_key)}

      :error ->
        {:reply, :ok, state}
    end
  end

  defp untrack_mirrored(state, tracked_key, pid, topic_raw, key_raw) do
    state.phoenix_mirror.untrack(pid, topic_raw, to_string(key_raw))

    case Map.fetch(state.tracked, tracked_key) do
      {:ok, %Tracked{mirrored?: true} = tracked} ->
        Writer.untrack(
          state.conn,
          tracked.key,
          state.connection,
          tracked.topic,
          tracked.holder,
          tracked.lifetime,
          tracked.mutation_seq
        )

        {:reply, :ok, drop_tracked(state, tracked_key)}

      {:ok, %Tracked{mirrored?: false}} ->
        {:reply, :ok, drop_tracked(state, tracked_key)}

      :error ->
        {:reply, :ok, state}
    end
  end

  @impl GenServer
  def handle_info({:trogon_presence_reader, reader_pid, {:snapshot, _cursor, presences}}, state) do
    case Map.fetch(state.reader_pids, reader_pid) do
      {:ok, topic_raw} -> {:noreply, reinstall(state, topic_raw, presences)}
      :error -> {:noreply, state}
    end
  end

  def handle_info({:trogon_presence_reader, reader_pid, {:diff, _cursor, diff}}, state) do
    case Map.fetch(state.reader_pids, reader_pid) do
      {:ok, topic_raw} ->
        current = Map.get(state.presences, topic_raw, %{})
        updated = Presences.apply_diff(current, diff)
        state = put_presences(state, topic_raw, updated)
        broadcast_diff(state, topic_raw, diff)
        {:noreply, state}

      :error ->
        {:noreply, state}
    end
  end

  def handle_info({:DOWN, _ref, :process, pid, _reason}, state) do
    cond do
      Map.has_key?(state.reader_pids, pid) -> {:noreply, drop_reader(state, pid)}
      Map.has_key?(state.tracked_monitors, pid) -> {:noreply, release_tracked(state, pid)}
      true -> {:noreply, state}
    end
  end

  def handle_info(:heartbeat_tick, state) do
    Process.send_after(self(), :heartbeat_tick, state.heartbeat_ms)
    {:noreply, send_heartbeats(state)}
  end

  def handle_info(_message, state), do: {:noreply, state}

  defp handle_update(state, tracked_key, tracked, meta_or_fun) do
    with {:ok, new_meta} <- resolve_meta(meta_or_fun, tracked.meta) do
      case Writer.update(
             state.conn,
             tracked.key,
             state.connection,
             tracked.topic,
             tracked.holder,
             new_meta,
             tracked.lifetime,
             tracked.mutation_seq
           ) do
        {:ok, written} ->
          updated = %{
            tracked
            | meta: new_meta,
              mutation_seq: written.mutation_seq,
              phx_ref: written.phx_ref
          }

          state = put_tracked(state, tracked_key, updated)
          {:reply, {:ok, StoredRef.to_string(written.phx_ref)}, state}

        {:error, reason} ->
          {:reply, {:error, reason}, state}
      end
    else
      {:error, reason} -> {:reply, {:error, reason}, state}
    end
  end

  defp handle_update_mirrored(state, tracked_key, pid, topic_raw, key_raw, meta_or_fun, backend) do
    key_string = to_string(key_raw)

    case Map.fetch(state.tracked, tracked_key) do
      {:ok, tracked} ->
        case state.phoenix_mirror.update(pid, topic_raw, key_string, meta_or_fun) do
          {:ok, phoenix_ref} ->
            {state, updated} = mirror_update(state, tracked_key, tracked, meta_or_fun)
            public_ref = public_ref(backend, updated, phoenix_ref)
            {:reply, {:ok, public_ref}, state}

          {:error, reason} ->
            {:reply, {:error, reason}, state}
        end

      :error ->
        {:reply, {:error, :nopresence}, state}
    end
  end

  defp mirror_update(
         state,
         tracked_key,
         %Tracked{mirrored?: true, meta: meta} = tracked,
         meta_or_fun
       )
       when not is_nil(meta) do
    case resolve_meta(meta_or_fun, tracked.meta) do
      {:ok, new_meta} ->
        case Writer.update(
               state.conn,
               tracked.key,
               state.connection,
               tracked.topic,
               tracked.holder,
               new_meta,
               tracked.lifetime,
               tracked.mutation_seq
             ) do
          {:ok, written} ->
            updated = %{
              tracked
              | meta: new_meta,
                mutation_seq: written.mutation_seq,
                phx_ref: written.phx_ref
            }

            {put_tracked(state, tracked_key, updated), updated}

          {:error, reason} ->
            Logger.warning(
              "could not mirror an update to NATS for #{tracked.topic_raw}/#{tracked.key_raw}: #{inspect(reason)}"
            )

            updated = %{
              tracked
              | meta: new_meta,
                mirrored?: false,
                topic: nil,
                key: nil,
                holder: nil,
                lifetime: nil,
                mutation_seq: nil
            }

            {put_tracked(state, tracked_key, updated), updated}
        end

      {:error, _reason} ->
        {state, tracked}
    end
  end

  defp mirror_update(state, tracked_key, %Tracked{mirrored?: false} = tracked, meta_or_fun) do
    current_meta = tracked.meta || %{}

    case resolve_meta(meta_or_fun, current_meta) do
      {:ok, new_meta} ->
        updated = %{tracked | meta: new_meta}
        {put_tracked(state, tracked_key, updated), updated}

      {:error, _reason} ->
        {state, tracked}
    end
  end

  defp resolve_meta(fun, current_meta) when is_function(fun, 1),
    do: Meta.new(fun.(Meta.to_map(current_meta)))

  defp resolve_meta(map, _current_meta) when is_map(map), do: Meta.new(map)

  defp put_tracked(state, tracked_key, %Tracked{} = tracked) do
    state
    |> monitor_holder(tracked.pid)
    |> Map.put(:tracked, Map.put(state.tracked, tracked_key, tracked))
  end

  defp drop_tracked(state, tracked_key) do
    %{state | tracked: Map.delete(state.tracked, tracked_key)}
  end

  defp monitor_holder(state, pid) do
    if Map.has_key?(state.tracked_monitors, pid) do
      state
    else
      ref = Process.monitor(pid)
      %{state | tracked_monitors: Map.put(state.tracked_monitors, pid, ref)}
    end
  end

  defp release_tracked(state, pid) do
    {owned, remaining} =
      Enum.split_with(state.tracked, fn {{entry_pid, _topic, _key}, _tracked} ->
        entry_pid == pid
      end)

    Enum.each(owned, fn {_tracked_key, tracked} ->
      if tracked.mirrored? do
        Writer.untrack(
          state.conn,
          tracked.key,
          state.connection,
          tracked.topic,
          tracked.holder,
          tracked.lifetime,
          tracked.mutation_seq
        )
      end
    end)

    %{
      state
      | tracked: Map.new(remaining),
        tracked_monitors: Map.delete(state.tracked_monitors, pid)
    }
  end

  defp ensure_reader(state, %Topic{} = topic) do
    topic_raw = Topic.raw(topic)

    if Map.has_key?(state.readers, topic_raw) do
      state
    else
      start_reader(state, topic, topic_raw)
    end
  end

  defp start_reader(state, topic, topic_raw) do
    reader_opts =
      [
        conn: state.conn,
        key: state.reader_key,
        connection: state.connection,
        topic: topic,
        shards: state.shards,
        limits: state.limits,
        subscribers: [self()]
      ]
      |> maybe_put_resnapshot_ms(state.resnapshot_ms)

    case Reader.start_link(reader_opts) do
      {:ok, reader_pid} ->
        Process.monitor(reader_pid)

        %{
          state
          | readers: Map.put(state.readers, topic_raw, reader_pid),
            reader_pids: Map.put(state.reader_pids, reader_pid, topic_raw)
        }

      {:error, reason} ->
        Logger.warning(
          "could not start a trogon_presence reader for #{topic_raw}: #{inspect(reason)}"
        )

        state
    end
  end

  defp maybe_put_resnapshot_ms(opts, nil), do: opts
  defp maybe_put_resnapshot_ms(opts, ms), do: Keyword.put(opts, :resnapshot_ms, ms)

  defp drop_reader(state, reader_pid) do
    case Map.fetch(state.reader_pids, reader_pid) do
      {:ok, topic_raw} ->
        %{
          state
          | readers: Map.delete(state.readers, topic_raw),
            reader_pids: Map.delete(state.reader_pids, reader_pid),
            presences: Map.delete(state.presences, topic_raw)
        }

      :error ->
        state
    end
  end

  defp reinstall(state, topic_raw, presences) do
    case Map.fetch(state.presences, topic_raw) do
      {:ok, previous} ->
        diff = Diff.between(previous, presences)
        state = put_presences(state, topic_raw, presences)
        unless Diff.empty?(diff), do: broadcast_diff(state, topic_raw, diff)
        state

      :error ->
        put_presences(state, topic_raw, presences)
    end
  end

  defp put_presences(state, topic_raw, presences) do
    %{state | presences: Map.put(state.presences, topic_raw, presences)}
  end

  defp broadcast_diff(state, topic_raw, diff) do
    payload = Broadcast.diff_payload(diff)

    Phoenix.PubSub.local_broadcast(
      state.pubsub_server,
      topic_raw,
      Broadcast.broadcast(topic_raw, payload),
      state.dispatcher
    )
  end

  defp send_heartbeats(state) do
    {mirrored, unmirrored} = Enum.split_with(Map.values(state.tracked), & &1.mirrored?)

    state =
      mirrored
      |> Enum.group_by(& &1.key)
      |> Enum.reduce(state, fn {key, entries}, state ->
        wire_entries = Enum.map(entries, &{&1.holder, &1.topic, &1.lifetime, &1.mutation_seq})

        case Writer.heartbeat(state.conn, key, state.connection, wire_entries) do
          {:ok, %HeartbeatReply{entries: statuses}} ->
            entries
            |> Enum.zip(statuses)
            |> Enum.reduce(state, &apply_heartbeat_status(&2, &1))

          {:error, reason} ->
            Logger.warning("heartbeat request failed for #{inspect(key)}: #{inspect(reason)}")
            state
        end
      end)

    Enum.reduce(unmirrored, state, &repair_mirror/2)
  end

  defp apply_heartbeat_status(state, {%Tracked{} = tracked, status})
       when status in ["gone", "conflict"],
       do: retrack(state, tracked)

  defp apply_heartbeat_status(state, {%Tracked{}, _status}), do: state

  defp repair_mirror(%Tracked{meta: nil}, state), do: state

  defp repair_mirror(%Tracked{} = tracked, state) do
    tracked_key = {tracked.pid, tracked.topic_raw, tracked.key_raw}

    with {:ok, topic} <- Topic.new(tracked.topic_raw),
         {:ok, key} <- Key.new(tracked.key_raw) do
      holder = HolderId.generate()

      case Writer.track(state.conn, key, state.connection, topic, holder, tracked.meta) do
        {:ok, written} ->
          updated = %{
            tracked
            | mirrored?: true,
              topic: topic,
              key: key,
              holder: holder,
              lifetime: written.lifetime,
              mutation_seq: written.mutation_seq,
              phx_ref: written.phx_ref
          }

          %{state | tracked: Map.put(state.tracked, tracked_key, updated)}

        {:error, reason} ->
          Logger.warning(
            "could not repair the NATS mirror for #{tracked.topic_raw}/#{tracked.key_raw}: #{inspect(reason)}"
          )

          state
      end
    else
      {:error, _reason} -> state
    end
  end

  defp retrack(state, %Tracked{} = tracked) do
    holder = HolderId.generate()

    case Writer.track(
           state.conn,
           tracked.key,
           state.connection,
           tracked.topic,
           holder,
           tracked.meta
         ) do
      {:ok, written} ->
        updated = %{
          tracked
          | holder: holder,
            lifetime: written.lifetime,
            mutation_seq: written.mutation_seq,
            phx_ref: written.phx_ref
        }

        tracked_key = {tracked.pid, tracked.topic_raw, tracked.key_raw}
        %{state | tracked: Map.put(state.tracked, tracked_key, updated)}

      {:error, reason} ->
        Logger.warning(
          "could not re-track a holder whose lease was lost for #{inspect(tracked.key)}: #{inspect(reason)}"
        )

        state
    end
  end
end
